// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgKCU1XeLfBweUuYfWZ1IsAFRMr4nAgM',
    appId: '1:194781732870:web:2163a1b15327efce206387',
    messagingSenderId: '194781732870',
    projectId: 'unibus-intermunicipal',
    authDomain: 'unibus-intermunicipal.firebaseapp.com',
    storageBucket: 'unibus-intermunicipal.firebasestorage.app',
    measurementId: 'G-BDXCGL98BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA55QO0y4H3hQ1XGfA0lag9uRgln8hU-mQ',
    appId: '1:194781732870:android:281ac5fc1adeb7ab206387',
    messagingSenderId: '194781732870',
    projectId: 'unibus-intermunicipal',
    storageBucket: 'unibus-intermunicipal.firebasestorage.app',
  );
}
